app = "chargerpulse"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "443"

[http_service]
  internal_port = 443
  force_https = true
  protocol = "tcp"

[[services.ports]]
  port = 443
  handlers = ["tls"]

[[services.tcp_checks]]
  grace_period = "10s"
  interval = "10s"
  timeout = "5s"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1